#!/bin/bash

# Async Vectorization - CURL Examples
# Contoh-contoh curl untuk testing async vectorization endpoints

BASE_URL="http://localhost:8000"

echo "╔════════════════════════════════════════════════════╗"
echo "║     Async Vectorization API - CURL Examples       ║"
echo "╚════════════════════════════════════════════════════╝"
echo ""

# ============================================================
# 1. START ASYNC VECTORIZATION
# ============================================================
echo "1️⃣  START ASYNC VECTORIZATION"
echo "═════════════════════════════════════════════════════"
echo ""
echo "Endpoint: POST /api/v1/vectorize-async"
echo "Description: Start vectorization di background (non-blocking)"
echo ""
echo "Command:"
echo "curl -X POST \"${BASE_URL}/api/v1/vectorize-async?batch_size=100\""
echo ""
echo "Quick test (save job_id):"
echo "JOB_ID=\$(curl -s -X POST \"${BASE_URL}/api/v1/vectorize-async\" | jq -r '.data.job_id')"
echo "echo \"Job ID: \$JOB_ID\""
echo ""
echo "Response: Returns job_id untuk polling status"
echo ""
echo "---"
echo ""

# ============================================================
# 2. CHECK JOB STATUS
# ============================================================
echo "2️⃣  CHECK JOB STATUS"
echo "═════════════════════════════════════════════════════"
echo ""
echo "Endpoint: GET /api/v1/vectorization-job/{job_id}/status"
echo "Description: Check progress vectorization"
echo ""
echo "Command:"
echo "curl -X GET \"${BASE_URL}/api/v1/vectorization-job/YOUR_JOB_ID/status\""
echo ""
echo "Pretty print dengan jq:"
echo "curl -s -X GET \"${BASE_URL}/api/v1/vectorization-job/YOUR_JOB_ID/status\" | jq '.data'"
echo ""
echo "Show only progress:"
echo "curl -s -X GET \"${BASE_URL}/api/v1/vectorization-job/YOUR_JOB_ID/status\" | jq '.data.progress'"
echo ""
echo "Show only elapsed time:"
echo "curl -s -X GET \"${BASE_URL}/api/v1/vectorization-job/YOUR_JOB_ID/status\" | jq '.data.elapsed_time_seconds'"
echo ""
echo "---"
echo ""

# ============================================================
# 3. CANCEL JOB
# ============================================================
echo "3️⃣  CANCEL PENDING JOB"
echo "═════════════════════════════════════════════════════"
echo ""
echo "Endpoint: DELETE /api/v1/vectorization-job/{job_id}/cancel"
echo "Description: Cancel pending job (only pending jobs)"
echo ""
echo "Command:"
echo "curl -X DELETE \"${BASE_URL}/api/v1/vectorization-job/YOUR_JOB_ID/cancel\""
echo ""
echo "---"
echo ""

# ============================================================
# 4. LIST ALL JOBS
# ============================================================
echo "4️⃣  LIST ALL VECTORIZATION JOBS"
echo "═════════════════════════════════════════════════════"
echo ""
echo "Endpoint: GET /api/v1/vectorization-jobs"
echo "Description: Show all jobs (pending, running, completed)"
echo ""
echo "Command:"
echo "curl -X GET \"${BASE_URL}/api/v1/vectorization-jobs\""
echo ""
echo "Pretty print:"
echo "curl -s -X GET \"${BASE_URL}/api/v1/vectorization-jobs\" | jq '.data'"
echo ""
echo "Show only active jobs:"
echo "curl -s -X GET \"${BASE_URL}/api/v1/vectorization-jobs\" | jq '.active_jobs'"
echo ""
echo "---"
echo ""

# ============================================================
# COMPLETE WORKFLOWS
# ============================================================
echo "╔════════════════════════════════════════════════════╗"
echo "║        Complete Workflows with Bash               ║"
echo "╚════════════════════════════════════════════════════╝"
echo ""

# Workflow 1: Simple Start & Poll
echo "WORKFLOW 1: Start & Poll Until Complete"
echo "════════════════════════════════════════"
echo ""
echo "#!/bin/bash"
echo ""
echo "# 1. Start vectorization"
echo "echo \"Starting vectorization...\""
echo "JOB_ID=\$(curl -s -X POST \"${BASE_URL}/api/v1/vectorize-async\" | jq -r '.data.job_id')"
echo "echo \"Job ID: \$JOB_ID\""
echo ""
echo "# 2. Poll status until complete"
echo "while true; do"
echo "  STATUS=\$(curl -s -X GET \"${BASE_URL}/api/v1/vectorization-job/\$JOB_ID/status\" | jq '.data')"
echo "  JOB_STATUS=\$(echo \"\$STATUS\" | jq -r '.status')"
echo "  PROGRESS=\$(echo \"\$STATUS\" | jq '.progress.progress_percentage')"
echo "  ELAPSED=\$(echo \"\$STATUS\" | jq '.elapsed_time_seconds')"
echo "  "
echo "  printf \"Status: %-10s | Progress: %6.1f%% | Elapsed: %6.1fs\\r\" \"\$JOB_STATUS\" \"\$PROGRESS\" \"\$ELAPSED\""
echo "  "
echo "  if [ \"\$JOB_STATUS\" = \"completed\" ] || [ \"\$JOB_STATUS\" = \"failed\" ]; then"
echo "    echo \"\""
echo "    echo \"Job finished with status: \$JOB_STATUS\""
echo "    break"
echo "  fi"
echo "  "
echo "  sleep 5"
echo "done"
echo ""
echo "---"
echo ""

# Workflow 2: With Error Handling
echo "WORKFLOW 2: Start, Poll dengan Error Handling"
echo "═════════════════════════════════════════════"
echo ""
echo "#!/bin/bash"
echo ""
echo "BASE_URL=\"${BASE_URL}\""
echo "TIMEOUT=3600  # 1 hour timeout"
echo "INTERVAL=5"
echo "ELAPSED=0"
echo ""
echo "# Start"
echo "echo \"Starting vectorization...\""
echo "RESPONSE=\$(curl -s -X POST \"\$BASE_URL/api/v1/vectorize-async\")"
echo "if [ \$? -ne 0 ]; then"
echo "  echo \"Error: Failed to start vectorization\""
echo "  exit 1"
echo "fi"
echo ""
echo "JOB_ID=\$(echo \"\$RESPONSE\" | jq -r '.data.job_id')"
echo "if [ -z \"\$JOB_ID\" ] || [ \"\$JOB_ID\" = \"null\" ]; then"
echo "  echo \"Error: Failed to get job_id\""
echo "  echo \"Response: \$RESPONSE\""
echo "  exit 1"
echo "fi"
echo ""
echo "echo \"Job started: \$JOB_ID\""
echo ""
echo "# Poll"
echo "while [ \$ELAPSED -lt \$TIMEOUT ]; do"
echo "  STATUS=\$(curl -s -X GET \"\$BASE_URL/api/v1/vectorization-job/\$JOB_ID/status\" | jq '.data')"
echo "  JOB_STATUS=\$(echo \"\$STATUS\" | jq -r '.status')"
echo "  "
echo "  case \"\$JOB_STATUS\" in"
echo "    pending)"
echo "      echo \"Job pending...\""
echo "      ;;"
echo "    running)"
echo "      PROGRESS=\$(echo \"\$STATUS\" | jq '.progress.progress_percentage')"
echo "      echo \"Progress: \$PROGRESS%\""
echo "      ;;"
echo "    completed)"
echo "      echo \"Job completed!\""
echo "      echo \"\$STATUS\" | jq '.result'"
echo "      exit 0"
echo "      ;;"
echo "    failed)"
echo "      echo \"Job failed!\""
echo "      echo \"\$STATUS\" | jq '.error'"
echo "      exit 1"
echo "      ;;"
echo "  esac"
echo "  "
echo "  sleep \$INTERVAL"
echo "  ELAPSED=\$((ELAPSED + INTERVAL))"
echo "done"
echo ""
echo "echo \"Error: Job timeout after \$TIMEOUT seconds\""
echo "exit 1"
echo ""
echo "---"
echo ""

# Workflow 3: Detailed Status Check
echo "WORKFLOW 3: Detailed Status Monitoring"
echo "═════════════════════════════════════"
echo ""
echo "#!/bin/bash"
echo ""
echo "JOB_ID=\"\$1\""
echo "if [ -z \"\$JOB_ID\" ]; then"
echo "  echo \"Usage: \$0 <job_id>\""
echo "  exit 1"
echo "fi"
echo ""
echo "curl -s -X GET \"${BASE_URL}/api/v1/vectorization-job/\$JOB_ID/status\" | jq '{"
echo "  status: .data.status,"
echo "  progress_percent: .data.progress.progress_percentage,"
echo "  processed: .data.progress.processed_papers,"
echo "  total: .data.progress.total_papers,"
echo "  current_batch: .data.progress.current_batch,"
echo "  total_batches: .data.progress.total_batches,"
echo "  elapsed_seconds: .data.elapsed_time_seconds,"
echo "  result: .data.result,"
echo "  error: .data.error"
echo "}'"
echo ""
echo "---"
echo ""

# ============================================================
# USEFUL COMMANDS
# ============================================================
echo "╔════════════════════════════════════════════════════╗"
echo "║        Useful One-Liners                          ║"
echo "╚════════════════════════════════════════════════════╝"
echo ""

echo "💡 Start vectorization dan save job ID:"
echo "JOB_ID=\$(curl -s -X POST \"${BASE_URL}/api/v1/vectorize-async\" | jq -r '.data.job_id'); echo \$JOB_ID"
echo ""

echo "💡 Check if job is completed:"
echo "curl -s -X GET \"${BASE_URL}/api/v1/vectorization-job/JOB_ID/status\" | jq '.data.status'"
echo ""

echo "💡 Get progress percentage:"
echo "curl -s -X GET \"${BASE_URL}/api/v1/vectorization-job/JOB_ID/status\" | jq '.data.progress.progress_percentage'"
echo ""

echo "💡 Get elapsed time:"
echo "curl -s -X GET \"${BASE_URL}/api/v1/vectorization-job/JOB_ID/status\" | jq '.data.elapsed_time_seconds'"
echo ""

echo "💡 Get result (if completed):"
echo "curl -s -X GET \"${BASE_URL}/api/v1/vectorization-job/JOB_ID/status\" | jq '.data.result'"
echo ""

echo "💡 Get error (if failed):"
echo "curl -s -X GET \"${BASE_URL}/api/v1/vectorization-job/JOB_ID/status\" | jq '.data.error'"
echo ""

echo "💡 List active jobs:"
echo "curl -s -X GET \"${BASE_URL}/api/v1/vectorization-jobs\" | jq '.data[] | select(.status==\"running\")'\"
echo ""

echo "💡 Count total jobs:"
echo "curl -s -X GET \"${BASE_URL}/api/v1/vectorization-jobs\" | jq '.total_jobs'"
echo ""

echo "💡 Cancel a job:"
echo "curl -X DELETE \"${BASE_URL}/api/v1/vectorization-job/JOB_ID/cancel\""
echo ""

# ============================================================
# COMPARISON: SYNC vs ASYNC
# ============================================================
echo ""
echo "╔════════════════════════════════════════════════════╗"
echo "║     Sync vs Async Vectorization                   ║"
echo "╚════════════════════════════════════════════════════╝"
echo ""

echo "SYNCHRONOUS (POST /vectorize-all-papers):"
echo "────────────────────────────────────────"
echo "curl -X POST \"${BASE_URL}/api/v1/vectorize-all-papers?batch_size=100\""
echo ""
echo "✗ Blocking request (5-15 minutes)"
echo "✗ Will timeout untuk large datasets"
echo "✗ Client harus tunggu"
echo "✓ Direct result response"
echo ""

echo "ASYNCHRONOUS (POST /vectorize-async):"
echo "──────────────────────────────────────"
echo "curl -X POST \"${BASE_URL}/api/v1/vectorize-async?batch_size=100\""
echo ""
echo "✓ Non-blocking (immediate response)"
echo "✓ Tidak akan timeout"
echo "✓ Progress tracking"
echo "✓ Bisa multiple concurrent jobs"
echo "✗ Perlu polling untuk result"
echo ""

echo "REKOMENDASI:"
echo "────────────"
echo "- Gunakan ASYNC untuk production (lebih reliable)"
echo "- Gunakan SYNC untuk testing dengan small dataset"
echo ""

echo ""
echo "╔════════════════════════════════════════════════════╗"
echo "║           End of CURL Examples                    ║"
echo "╚════════════════════════════════════════════════════╝"
echo ""
echo "For detailed guide: ASYNC_VECTORIZATION_GUIDE.md"
echo ""
