"""empty message

Revision ID: 168f8c79ae39
Revises: 079833840332
Create Date: 2026-02-28 14:09:38.540844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '168f8c79ae39'
down_revision: Union[str, Sequence[str], None] = '079833840332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_created_at'), table_name='users')
    op.drop_index(op.f('ix_user_id'), table_name='users')
    op.drop_index(op.f('ix_user_password'), table_name='users')
    op.drop_index(op.f('ix_user_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_admin_created_at'), table_name='admin')
    op.drop_index(op.f('ix_admin_id'), table_name='admin')
    op.drop_index(op.f('ix_admin_password'), table_name='admin')
    op.drop_index(op.f('ix_admin_role'), table_name='admin')
    op.drop_index(op.f('ix_admin_username'), table_name='admin')
    op.drop_table('admin')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedback_paper_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedback_response'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_paper_abstract'), table_name='papers', mysql_length={'abstract': 768})
    op.drop_index(op.f('ix_paper_category'), table_name='papers')
    op.drop_index(op.f('ix_paper_created_at'), table_name='papers')
    op.drop_index(op.f('ix_paper_id'), table_name='papers')
    op.drop_index(op.f('ix_paper_published_date'), table_name='papers')
    op.drop_index(op.f('ix_paper_title'), table_name='papers')
    op.drop_index(op.f('ix_paper_url'), table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_evaluation_created_at'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluation_feedback_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluation_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluation_metric_name'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluation_score'), table_name='evaluations')
    op.drop_table('evaluations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('metric_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('feedback_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], name=op.f('fk_evaluation_feedback_ids')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_evaluation_score'), 'evaluations', ['score'], unique=False)
    op.create_index(op.f('ix_evaluation_metric_name'), 'evaluations', ['metric_name'], unique=False)
    op.create_index(op.f('ix_evaluation_id'), 'evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_evaluation_feedback_id'), 'evaluations', ['feedback_id'], unique=False)
    op.create_index(op.f('ix_evaluation_created_at'), 'evaluations', ['created_at'], unique=False)
    op.create_table('papers',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('abstract', mysql.TEXT(), nullable=False),
    sa.Column('published_date', mysql.DATETIME(), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('author', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_paper_url'), 'papers', ['url'], unique=False)
    op.create_index(op.f('ix_paper_title'), 'papers', ['title'], unique=False)
    op.create_index(op.f('ix_paper_published_date'), 'papers', ['published_date'], unique=False)
    op.create_index(op.f('ix_paper_id'), 'papers', ['id'], unique=False)
    op.create_index(op.f('ix_paper_created_at'), 'papers', ['created_at'], unique=False)
    op.create_index(op.f('ix_paper_category'), 'papers', ['category'], unique=False)
    op.create_index(op.f('ix_paper_abstract'), 'papers', ['abstract'], unique=False, mysql_length={'abstract': 768})
    op.create_table('feedbacks',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('response', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('paper_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_paper_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feedbacks_id_users')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_feedback_user_id'), 'feedbacks', ['user_id'], unique=False)
    op.create_index(op.f('ix_feedback_response'), 'feedbacks', ['response'], unique=False)
    op.create_index(op.f('ix_feedback_paper_id'), 'feedbacks', ['paper_id'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_created_at'), 'feedbacks', ['created_at'], unique=False)
    op.create_table('admin',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_admin_username'), 'admin', ['username'], unique=False)
    op.create_index(op.f('ix_admin_role'), 'admin', ['role'], unique=False)
    op.create_index(op.f('ix_admin_password'), 'admin', ['password'], unique=True)
    op.create_index(op.f('ix_admin_id'), 'admin', ['id'], unique=False)
    op.create_index(op.f('ix_admin_created_at'), 'admin', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('ix_user_password'), 'users', ['password'], unique=True)
    op.create_index(op.f('ix_user_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_user_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###
