"""added recommendation log table

Revision ID: 2f8d609f4e69
Revises: 168f8c79ae39
Create Date: 2026-04-25 20:42:39.035188

"""
import datetime
from typing import Sequence, Union

from sqlalchemy.dialects import mysql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f8d609f4e69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('recommendations', mysql.JSON(), nullable=False),
        sa.Column('relevants', mysql.JSON(), nullable=True),
        sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",name="fk_evaluation_id_users"),index=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
