"""merge 2 heads

Revision ID: a9a5291743f0
Revises: 079833840332, 2f8d609f4e69
Create Date: 2026-04-25 22:55:45.563105

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a5291743f0'
down_revision: Union[str, Sequence[str], None] = ('079833840332', '2f8d609f4e69')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('recommendations', mysql.JSON(), nullable=False),
        sa.Column('relevants', mysql.JSON(), nullable=True),
        sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",name="fk_evaluation_id_users"),index=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
    )
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    pass
